config/routes.rb
Rails.application.routes.draw do
  resources :assignsubmission_files
  resources :assignment_submissions
  resources :mdl_files
  resources :contexts
  resources :courses do
    member do
      get 'courses/add_course/:id', to: 'courses#addCourse', as: 'add_course'
    end
    collection do
      get 'courses/register_course/:id', to: 'courses#registerCourse', as: 'register_course'
    end
  end
  resources :events
  resources :forum_discussions
  resources :forum_posts
  resources :forums
  resources :resources
  resources :role_assignments
  resources :users

  root 'welcome#index'

  get 'users/vEmail/:id', to: 'users#vEmail'

  get 'users/vContrasena/:email', to: 'users#vContrasena'

  post 'users/contrasena', to: 'users#contrasena'

  post 'users/email', to: 'users#email'

  get 'users/emailErroneo', to: 'users#emailErroneo'

  get 'users/contrasenaErronea', to: 'users#contrasenaErronea'

  get 'contexts/course/:id', to: 'contexts#course'

  get 'resources/recursosPorCurso/:course', to: 'resources#recursosPorCurso'

  get 'events/eventosPorCurso/:courseid', to: 'events#eventosPorCurso'

  get 'events/eventosDetalle/:eventid/:courseid', to: 'events#eventosDetalle'

  get 'forums/forosPorCurso/:course', to: 'forums#forosPorCurso'

  get 'forum_discussions/discusionesPorForo/:forum', to: 'forum_discussions#discusionesPorForo'

  get 'forum_posts/postPorDiscusionPrincipal/:discussion', to: 'forum_posts#postPorDiscusionPrincipal'

  get 'forum_posts/postRespuestas/:discussion', to: 'forum_posts#postRespuestas'

  get 'forum_posts/sinPosts', to: 'forum_posts#sinPosts'

  get 'forum_discussions/sinDiscusiones', to: 'forum_discussions#sinDiscusiones'

  get 'events/sinEventos/:courseid', to: 'events#sinEventos'

  get 'resources/sinRecursos/:course', to: 'resources#sinRecursos'

  get 'contexts/sinCursos/:id', to: 'contexts#sinCursos'

  get 'courses/buscar/:id', to: 'courses#buscar'

  post 'courses/cursos', to: 'courses#cursos'

  get 'courses/sinCursos/', to: 'courses#sinCursos'

  get 'forum_posts/felicitaciones', to: 'forum_posts#felicitaciones'

  get 'forum_posts/error', to: 'forum_posts#error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'resources/descarga/:course/:timemodified', to: 'resources#descarga'

  get 'resources/descargaINT/:variablePatito', to: 'resources#descargaINT'

  get 'events/emailProf/:id', to: 'events#emailProf'

  post 'events/enviarCorreo', to: 'events#enviarCorreo'

  get 'events/envioExitoso/:courseid', to: 'events#envioExitoso'

  match 'enviarCorreo', to: 'event#send_mail', via: 'post'

  post 'uploadfiles'=>'events#upload'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignsubmission_file.rb
class AssignsubmissionFile < ApplicationRecord

  self.table_name = "assignsubmission_file"
end

app/models/context.rb
class Context < ApplicationRecord

  self.table_name = "context"

end

app/models/course.rb
class Course < ApplicationRecord

  self.table_name = "course"

end

app/models/event.rb
class Event < ApplicationRecord

  self.table_name = "event"
  belongs_to :user 

end

app/models/forum.rb
class Forum < ApplicationRecord

  self.table_name = "forum"
  self.inheritance_column = :_type_disabled

end

app/models/forum_discussion.rb
class ForumDiscussion < ApplicationRecord


end

app/models/forum_post.rb
class ForumPost < ApplicationRecord



end

app/models/mdl_file.rb
class MdlFile < ApplicationRecord

  self.table_name = "files"
  belongs_to :ressource

end

app/models/resource.rb
class Resource < ApplicationRecord

 self.table_name = "resource"

 has_many :MdlFile

end

app/models/role_assignment.rb
class RoleAssignment < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord


   self.table_name = "user"
   has_many :events


end

app/controllers/assignsubmission_files_controller.rb
class AssignsubmissionFilesController < ApplicationController
  before_action :set_assignsubmission_file, only: [:show, :edit, :update, :destroy]

  # GET /assignsubmission_files
  # GET /assignsubmission_files.json
  def index
    @assignsubmission_files = AssignsubmissionFile.all
  end

  # GET /assignsubmission_files/1
  # GET /assignsubmission_files/1.json
  def show
  end

  # GET /assignsubmission_files/new
  def new
    @assignsubmission_file = AssignsubmissionFile.new
  end

  # GET /assignsubmission_files/1/edit
  def edit
  end

  # POST /assignsubmission_files
  # POST /assignsubmission_files.json
  def create
    @assignsubmission_file = AssignsubmissionFile.new(assignsubmission_file_params)

    respond_to do |format|
      if @assignsubmission_file.save
        format.html { redirect_to @assignsubmission_file, notice: 'Assignsubmission file was successfully created.' }
        format.json { render :show, status: :created, location: @assignsubmission_file }
      else
        format.html { render :new }
        format.json { render json: @assignsubmission_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignsubmission_files/1
  # PATCH/PUT /assignsubmission_files/1.json
  def update
    respond_to do |format|
      if @assignsubmission_file.update(assignsubmission_file_params)
        format.html { redirect_to @assignsubmission_file, notice: 'Assignsubmission file was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignsubmission_file }
      else
        format.html { render :edit }
        format.json { render json: @assignsubmission_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignsubmission_files/1
  # DELETE /assignsubmission_files/1.json
  def destroy
    @assignsubmission_file.destroy
    respond_to do |format|
      format.html { redirect_to assignsubmission_files_url, notice: 'Assignsubmission file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignsubmission_file
      @assignsubmission_file = AssignsubmissionFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignsubmission_file_params
      params.require(:assignsubmission_file).permit(:assignment, :submission, :numfiles)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignsubmission_files_helper.rb
module AssignsubmissionFilesHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/mdl_files_helper.rb
module MdlFilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignsubmission_files/_form.html.erb
<%= form_with(model: assignsubmission_file, local: true) do |form| %>
  <% if assignsubmission_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignsubmission_file.errors.count, "error") %> prohibited this assignsubmission_file from being saved:</h2>

      <ul>
      <% assignsubmission_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :assignment %>
    <%= form.text_field :assignment %>
  </div>

  <div class="field">
    <%= form.label :submission %>
    <%= form.text_field :submission %>
  </div>

  <div class="field">
    <%= form.label :numfiles %>
    <%= form.text_field :numfiles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assignsubmission_files/edit.html.erb
<h1>Editing Assignsubmission File</h1>

<%= render 'form', assignsubmission_file: @assignsubmission_file %>

<%= link_to 'Show', @assignsubmission_file %> |
<%= link_to 'Back', assignsubmission_files_path %>

app/views/assignsubmission_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignsubmission Files</h1>

<table>
  <thead>
    <tr>
      <th>Assignment</th>
      <th>Submission</th>
      <th>Numfiles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignsubmission_files.each do |assignsubmission_file| %>
      <tr>
        <td><%= assignsubmission_file.assignment %></td>
        <td><%= assignsubmission_file.submission %></td>
        <td><%= assignsubmission_file.numfiles %></td>
        <td><%= link_to 'Show', assignsubmission_file %></td>
        <td><%= link_to 'Edit', edit_assignsubmission_file_path(assignsubmission_file) %></td>
        <td><%= link_to 'Destroy', assignsubmission_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignsubmission File', new_assignsubmission_file_path %>

app/views/assignsubmission_files/new.html.erb
<h1>New Assignsubmission File</h1>

<%= render 'form', assignsubmission_file: @assignsubmission_file %>

<%= link_to 'Back', assignsubmission_files_path %>

app/views/assignsubmission_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Assignment:</strong>
  <%= @assignsubmission_file.assignment %>
</p>

<p>
  <strong>Submission:</strong>
  <%= @assignsubmission_file.submission %>
</p>

<p>
  <strong>Numfiles:</strong>
  <%= @assignsubmission_file.numfiles %>
</p>

<%= link_to 'Edit', edit_assignsubmission_file_path(@assignsubmission_file) %> |
<%= link_to 'Back', assignsubmission_files_path %>