config/routes.rb
Rails.application.routes.draw do
  resources :assignsubmission_files
  resources :assignment_submissions
  resources :mdl_files
  resources :contexts
  resources :courses do
    member do
      get 'courses/add_course/:id', to: 'courses#addCourse', as: 'add_course'
    end
    collection do
      get 'courses/register_course/:id', to: 'courses#registerCourse', as: 'register_course'
    end
  end
  resources :events
  resources :forum_discussions
  resources :forum_posts
  resources :forums
  resources :resources
  resources :role_assignments
  resources :users

  root 'welcome#index'

  get 'users/vEmail/:id', to: 'users#vEmail'

  get 'users/vContrasena/:email', to: 'users#vContrasena'

  post 'users/contrasena', to: 'users#contrasena'

  post 'users/email', to: 'users#email'

  get 'users/emailErroneo', to: 'users#emailErroneo'

  get 'users/contrasenaErronea', to: 'users#contrasenaErronea'

  get 'contexts/course/:id', to: 'contexts#course'

  get 'resources/recursosPorCurso/:course', to: 'resources#recursosPorCurso'

  get 'events/eventosPorCurso/:courseid', to: 'events#eventosPorCurso'

  get 'events/eventosDetalle/:eventid/:courseid', to: 'events#eventosDetalle'

  get 'forums/forosPorCurso/:course', to: 'forums#forosPorCurso'

  get 'forum_discussions/discusionesPorForo/:forum', to: 'forum_discussions#discusionesPorForo'

  get 'forum_posts/postPorDiscusionPrincipal/:discussion', to: 'forum_posts#postPorDiscusionPrincipal'

  get 'forum_posts/postRespuestas/:discussion', to: 'forum_posts#postRespuestas'

  get 'forum_posts/sinPosts', to: 'forum_posts#sinPosts'

  get 'forum_discussions/sinDiscusiones', to: 'forum_discussions#sinDiscusiones'

  get 'events/sinEventos/:courseid', to: 'events#sinEventos'

  get 'resources/sinRecursos/:course', to: 'resources#sinRecursos'

  get 'contexts/sinCursos/:id', to: 'contexts#sinCursos'

  get 'courses/buscar/:id', to: 'courses#buscar'

  post 'courses/cursos', to: 'courses#cursos'

  get 'courses/sinCursos/', to: 'courses#sinCursos'

  get 'forum_posts/felicitaciones', to: 'forum_posts#felicitaciones'

  get 'forum_posts/error', to: 'forum_posts#error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'resources/descarga/:course/:timemodified', to: 'resources#descarga'

  get 'resources/descargaINT/:variablePatito', to: 'resources#descargaINT'

  get 'events/emailProf/:id', to: 'events#emailProf'

  post 'events/enviarCorreo', to: 'events#enviarCorreo'

  get 'events/envioExitoso/:courseid', to: 'events#envioExitoso'

  match 'enviarCorreo', to: 'event#send_mail', via: 'post'

  post 'uploadfiles'=>'events#upload'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord

  self.table_name = "context"

end

app/models/course.rb
class Course < ApplicationRecord

  self.table_name = "course"

end

app/models/event.rb
class Event < ApplicationRecord

  self.table_name = "event"
  belongs_to :user 

end

app/models/forum.rb
class Forum < ApplicationRecord

  self.table_name = "forum"
  self.inheritance_column = :_type_disabled

end

app/models/forum_discussion.rb
class ForumDiscussion < ApplicationRecord


end

app/models/forum_post.rb
class ForumPost < ApplicationRecord



end

app/models/mdl_file.rb
class MdlFile < ApplicationRecord

  self.table_name = "files"
  belongs_to :ressource

end

app/models/resource.rb
class Resource < ApplicationRecord

 self.table_name = "resource"

 has_many :MdlFile

end

app/models/role_assignment.rb
class RoleAssignment < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord


   self.table_name = "user"
   has_many :events


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/mdl_files_helper.rb
module MdlFilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/resources/_downloadalert.js.erb
window.location.href = "<%= @url %>"

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :intro %>
    <%= form.text_area :intro %>
  </div>

  <div class="field">
    <%= form.label :introformat %>
    <%= form.number_field :introformat %>
  </div>

  <div class="field">
    <%= form.label :tobemigrated %>
    <%= form.number_field :tobemigrated %>
  </div>

  <div class="field">
    <%= form.label :legacyfiles %>
    <%= form.number_field :legacyfiles %>
  </div>

  <div class="field">
    <%= form.label :legacyfileslast %>
    <%= form.text_field :legacyfileslast %>
  </div>

  <div class="field">
    <%= form.label :display %>
    <%= form.number_field :display %>
  </div>

  <div class="field">
    <%= form.label :displayoptions %>
    <%= form.text_area :displayoptions %>
  </div>

  <div class="field">
    <%= form.label :filterfiles %>
    <%= form.number_field :filterfiles %>
  </div>

  <div class="field">
    <%= form.label :revision %>
    <%= form.text_field :revision %>
  </div>

  <div class="field">
    <%= form.label :timemodified %>
    <%= form.text_field :timemodified %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/descarga.html.erb
<%= stylesheet_link_tag "baseMensajes" %>
<div class="container-fluid">
<div class = "Estilo">

  <div  class="card">



    <div class="card-header"><h1>Descarga</h1></div>


    <div class="list-group list-group-flush">

      <div class="list-group-item">



             <div class="col-lg-12"><h1>En este se ha iniciado la descarga de tu material  </h1></div>
                 <%= link_to "Volver a materiales",{controller: "resources", action: "recursosPorCurso", course: params[:course]}, class: 'btn btn-primary btn-lg  btn-block'%>

       </div>
      </div>
      </div>
    </div>
    <script>

        setTimeout(function(){
          window.location.href = "http://localhost:3000/resources/descargaINT/2"
        }, 3000);

    </script>
</div>

app/views/resources/descargaINT.html.erb
<%= stylesheet_link_tag "baseMensajes" %>
<div class="container-fluid">
<div class = "Estilo">

  <div  class="card">


    <div class="card-header"><h1>Descarga</h1></div>


    <div class="list-group list-group-flush">

      <div class="list-group-item">


             <div class="col-lg-12"><h1>En este se ha iniciado la descarga de tu material </h1></div>
                 <%= link_to "Volver a materiales",{controller: "resources", action: "recursosPorCurso", course: params[:course]}, class: 'btn btn-primary btn-lg  btn-block'%>

       </div>
      </div>
      </div>
    </div>
</div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Intro</th>
      <th>Introformat</th>
      <th>Tobemigrated</th>
      <th>Legacyfiles</th>
      <th>Legacyfileslast</th>
      <th>Display</th>
      <th>Displayoptions</th>
      <th>Filterfiles</th>
      <th>Revision</th>
      <th>Timemodified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.course %></td>
        <td><%= resource.name %></td>
        <td><%= resource.intro %></td>
        <td><%= resource.introformat %></td>
        <td><%= resource.tobemigrated %></td>
        <td><%= resource.legacyfiles %></td>
        <td><%= resource.legacyfileslast %></td>
        <td><%= resource.display %></td>
        <td><%= resource.displayoptions %></td>
        <td><%= resource.filterfiles %></td>
        <td><%= resource.revision %></td>
        <td><%= resource.timemodified %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/recursosPorCurso.html.erb
<%= form_for :resources, :url => { :action => :recursosPorCurso } do |f| %>


<%= stylesheet_link_tag "basePantallas" %>

<nav class="header navbar">
     <li class="nav-item col-lg-6"><%= link_to "Volver a mis cursos", :back%></li>
     <li class="nav-item col-lg-6"><%= link_to "Ir a eventos", controller: "events", action: "eventosPorCurso", courseid:  params[:course]%></li>
</nav>

<div class="contenido container-fluid">
<div class="row">
  <div class="col-md-12 titulo"><h1>Materiales</h1></div>
</div>
<% @resources.each do |resources| %>
<div class="row area">

 <%= link_to resources.name, {controller: "resources", action: "descarga",  course: resources.course, timemodified: resources.timemodified}, class: "area" %>


</div>
<% end %>

</div>


<nav class= "footer navbar" >

     <li class="nav-item col-lg-6"><%= link_to "Mis cursos", {controller: "contexts", action: "course", id:  cookies[:userid]} %></li>
     <li class="nav-item col-lg-6"><%= link_to "Buscar cursos", {controller: "courses", action: "buscar", id: params[:course]} %></li>

</nav>
<% end %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @resource.course %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @resource.intro %>
</p>

<p>
  <strong>Introformat:</strong>
  <%= @resource.introformat %>
</p>

<p>
  <strong>Tobemigrated:</strong>
  <%= @resource.tobemigrated %>
</p>

<p>
  <strong>Legacyfiles:</strong>
  <%= @resource.legacyfiles %>
</p>

<p>
  <strong>Legacyfileslast:</strong>
  <%= @resource.legacyfileslast %>
</p>

<p>
  <strong>Display:</strong>
  <%= @resource.display %>
</p>

<p>
  <strong>Displayoptions:</strong>
  <%= @resource.displayoptions %>
</p>

<p>
  <strong>Filterfiles:</strong>
  <%= @resource.filterfiles %>
</p>

<p>
  <strong>Revision:</strong>
  <%= @resource.revision %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @resource.timemodified %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/sinRecursos.html.erb
<%= form_tag(controller: "resources", action: "sinRecursos", method: "get") do |f| %>

<%= stylesheet_link_tag "baseMensajes" %>
<div class="container-fluid">
<div class = "Estilo">

  <div  class="card">


    <div class="card-header"><h1>Sin recursos</h1></div>


    <div class="list-group list-group-flush">

    <div class="list-group-item">


             <div class="col-lg-12"><h1>En este momento no hay materiales disponibles para este curso </h1></div>
               <%= link_to("Ir a Eventos", {controller: 'events', action: 'eventosPorCurso', courseid: params[:course] } , class: 'btn btn-primary btn-lg  btn-block')%>
               <h1> </h1>

               <%= link_to("Volver a mis cursos", :back, class: 'btn btn-primary btn-lg  btn-block')%>

             </div>
            </div>
           </div>
         </div>
       </div>






<% end %>