config/routes.rb
Rails.application.routes.draw do
  resources :assignsubmission_files
  resources :assignment_submissions
  resources :mdl_files
  resources :contexts
  resources :courses do
    member do
      get 'courses/add_course/:id', to: 'courses#addCourse', as: 'add_course'
    end
    collection do
      get 'courses/register_course/:id', to: 'courses#registerCourse', as: 'register_course'
    end
  end
  resources :events
  resources :forum_discussions
  resources :forum_posts
  resources :forums
  resources :resources
  resources :role_assignments
  resources :users

  root 'welcome#index'

  get 'users/vEmail/:id', to: 'users#vEmail'

  get 'users/vContrasena/:email', to: 'users#vContrasena'

  post 'users/contrasena', to: 'users#contrasena'

  post 'users/email', to: 'users#email'

  get 'users/emailErroneo', to: 'users#emailErroneo'

  get 'users/contrasenaErronea', to: 'users#contrasenaErronea'

  get 'contexts/course/:id', to: 'contexts#course'

  get 'resources/recursosPorCurso/:course', to: 'resources#recursosPorCurso'

  get 'events/eventosPorCurso/:courseid', to: 'events#eventosPorCurso'

  get 'events/eventosDetalle/:eventid/:courseid', to: 'events#eventosDetalle'

  get 'forums/forosPorCurso/:course', to: 'forums#forosPorCurso'

  get 'forum_discussions/discusionesPorForo/:forum', to: 'forum_discussions#discusionesPorForo'

  get 'forum_posts/postPorDiscusionPrincipal/:discussion', to: 'forum_posts#postPorDiscusionPrincipal'

  get 'forum_posts/postRespuestas/:discussion', to: 'forum_posts#postRespuestas'

  get 'forum_posts/sinPosts', to: 'forum_posts#sinPosts'

  get 'forum_discussions/sinDiscusiones', to: 'forum_discussions#sinDiscusiones'

  get 'events/sinEventos/:courseid', to: 'events#sinEventos'

  get 'resources/sinRecursos/:course', to: 'resources#sinRecursos'

  get 'contexts/sinCursos/:id', to: 'contexts#sinCursos'

  get 'courses/buscar/:id', to: 'courses#buscar'

  post 'courses/cursos', to: 'courses#cursos'

  get 'courses/sinCursos/', to: 'courses#sinCursos'

  get 'forum_posts/felicitaciones', to: 'forum_posts#felicitaciones'

  get 'forum_posts/error', to: 'forum_posts#error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'resources/descarga/:course/:timemodified', to: 'resources#descarga'

  get 'resources/descargaINT/:variablePatito', to: 'resources#descargaINT'

  get 'events/emailProf/:id', to: 'events#emailProf'

  post 'events/enviarCorreo', to: 'events#enviarCorreo'

  get 'events/envioExitoso/:courseid', to: 'events#envioExitoso'

  match 'enviarCorreo', to: 'event#send_mail', via: 'post'

  post 'uploadfiles'=>'events#upload'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord

  self.table_name = "context"

end

app/models/course.rb
class Course < ApplicationRecord

  self.table_name = "course"

end

app/models/event.rb
class Event < ApplicationRecord

  self.table_name = "event"
  belongs_to :user 

end

app/models/forum.rb
class Forum < ApplicationRecord

  self.table_name = "forum"
  self.inheritance_column = :_type_disabled

end

app/models/forum_discussion.rb
class ForumDiscussion < ApplicationRecord


end

app/models/forum_post.rb
class ForumPost < ApplicationRecord



end

app/models/mdl_file.rb
class MdlFile < ApplicationRecord

  self.table_name = "files"
  belongs_to :ressource

end

app/models/resource.rb
class Resource < ApplicationRecord

 self.table_name = "resource"

 has_many :MdlFile

end

app/models/role_assignment.rb
class RoleAssignment < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord


   self.table_name = "user"
   has_many :events


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end
##############################################
def buscar



end

def cursos

@search = params[:fullname]

@course = Course.select( :id,:fullname).where("fullname like ?", "%#{@search}%")

if @course.nil? == true || @course.blank? == true

render :action =>"sinCursos"

else

return @course

  #render json: @course

end
end


def sinCursos



end

def addCourse
  @course = Course.select(:id, :fullname).where('id = ?', params[:id]).first
  @professor = User.select(:id, :firstname, :lastname, :email).joins('INNER JOIN role_assignments ra on user.id = ra.userid INNER JOIN context ctx on ra.contextid = ctx.id').where('ctx.contextlevel = 50 and ra.roleid = 3 and ctx.instanceid = ?', params[:id]).first
end

def registerCourse
  @course = Course.select(:id, :fullname).where('id = ?', params[:id]).first
  @alumn = User.select(:id, :firstname, :lastname, :email).find(cookies[:userid])
  @alumn_name = @alumn.firstname + ' ' + @alumn.lastname
  @professor = User.select(:id, :firstname, :lastname, :email).joins('INNER JOIN role_assignments ra on user.id = ra.userid INNER JOIN context ctx on ra.contextid = ctx.id').where('ctx.contextlevel = 50 and ra.roleid = 3 and ctx.instanceid = ?', params[:course_id]).first
  @professor_name = @professor.firstname + ' ' + @professor.lastname
  CourseMailer.with(email: @professor.email, alumn: @alumn_name, professor: @professor_name, course: @course.fullname).course_register_email.deliver_now!
end

##############################################

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:category, :sortorder, :fullname, :shortname, :idnumber, :summary, :summaryformat, :format, :showgrades, :newsitems, :startdate, :marker, :maxbytes, :legacyfiles, :showreports, :visible, :visibleold, :groupmode, :groupmodeforce, :defaultgroupingid, :lang, :calendartype, :theme, :timecreated, :timemodified, :requested, :enablecompletion, :completionnotify, :cacherev)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/mdl_files_helper.rb
module MdlFilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :sortorder %>
    <%= form.text_field :sortorder %>
  </div>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :shortname %>
    <%= form.text_field :shortname %>
  </div>

  <div class="field">
    <%= form.label :idnumber %>
    <%= form.text_field :idnumber %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="field">
    <%= form.label :summaryformat %>
    <%= form.number_field :summaryformat %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_field :format %>
  </div>

  <div class="field">
    <%= form.label :showgrades %>
    <%= form.number_field :showgrades %>
  </div>

  <div class="field">
    <%= form.label :newsitems %>
    <%= form.number_field :newsitems %>
  </div>

  <div class="field">
    <%= form.label :startdate %>
    <%= form.text_field :startdate %>
  </div>

  <div class="field">
    <%= form.label :marker %>
    <%= form.text_field :marker %>
  </div>

  <div class="field">
    <%= form.label :maxbytes %>
    <%= form.text_field :maxbytes %>
  </div>

  <div class="field">
    <%= form.label :legacyfiles %>
    <%= form.number_field :legacyfiles %>
  </div>

  <div class="field">
    <%= form.label :showreports %>
    <%= form.number_field :showreports %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div class="field">
    <%= form.label :visibleold %>
    <%= form.check_box :visibleold %>
  </div>

  <div class="field">
    <%= form.label :groupmode %>
    <%= form.number_field :groupmode %>
  </div>

  <div class="field">
    <%= form.label :groupmodeforce %>
    <%= form.number_field :groupmodeforce %>
  </div>

  <div class="field">
    <%= form.label :defaultgroupingid %>
    <%= form.text_field :defaultgroupingid %>
  </div>

  <div class="field">
    <%= form.label :lang %>
    <%= form.text_field :lang %>
  </div>

  <div class="field">
    <%= form.label :calendartype %>
    <%= form.text_field :calendartype %>
  </div>

  <div class="field">
    <%= form.label :theme %>
    <%= form.text_field :theme %>
  </div>

  <div class="field">
    <%= form.label :timecreated %>
    <%= form.text_field :timecreated %>
  </div>

  <div class="field">
    <%= form.label :timemodified %>
    <%= form.text_field :timemodified %>
  </div>

  <div class="field">
    <%= form.label :requested %>
    <%= form.check_box :requested %>
  </div>

  <div class="field">
    <%= form.label :enablecompletion %>
    <%= form.check_box :enablecompletion %>
  </div>

  <div class="field">
    <%= form.label :completionnotify %>
    <%= form.check_box :completionnotify %>
  </div>

  <div class="field">
    <%= form.label :cacherev %>
    <%= form.text_field :cacherev %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/addCourse.html.erb
<%= form_for :courses, :url => { :action => :cursos} do |f| %>


<%= stylesheet_link_tag "basePantallas" %>
<div class="contenido container-fluid">
  <div class="row">
    <div class="col-md-12 titulo"><h1>Curso: <%= @course.fullname %></h1></div>
  </div>
  <div class="row">
    <div class="col-md-12 titulo"><h1>Profesor: <%= @professor.firstname %> <%= @professor.lastname %></h1></div>
  </div>
  <div class="row">
    <div class="col-md-12 titulo">
      <h1><%= link_to 'Solicitar inscripción de curso', register_course_courses_path(cookies[:userid], course_id: @course.id) %></h1>
    </div>
  </div>

</div>


<nav class="footer navbar ">

  <nav class= "footer navbar" >

       <li class="nav-item col-lg-12"><%= link_to "Mis cursos", {controller: "contexts", action: "course", id:  cookies[:userid]} %></li>


  </nav>

</nav>

<% end %>

app/views/courses/buscar.html.erb
<%= form_tag(controller: "courses", action: "cursos", method: "post") do |f| %>

<%= stylesheet_link_tag "baseMensajes" %>
<div class="container-fluid">
<div class = "Estilo">


    <div  class="card">


      <div class="card-header"><h1>Buscar</h1></div>


      <div class="list-group list-group-flush">

        <div class="list-group-item">


                <div class="col-lg-12"><h1><%= label_tag("Ingresa el nombre del curso que quieras buscar") %> </h1></div>
                 <%=text_field_tag :fullname,nil, class: "entrada" %>
               <h1></h1>
                <%= submit_tag "Buscar", :class => "btn btn-primary btn-lg btn-block" %>

         </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>

app/views/courses/cursos.html.erb
<%= form_for :courses, :url => { :action => :cursos} do |f| %>


<%= stylesheet_link_tag "basePantallas" %>
<div class="contenido container-fluid">
<div class="row">
  <div class="col-md-12 titulo"><h1>Resultados de la busqueda</h1></div>
</div>
<% @course.each do |course| %>
<div class="row area">

  <%= link_to course.fullname, controller: "resources", action: "recursosPorCurso", course: course.id,class: "area"%>

</div>
<% end %>

</div>


<nav class="footer navbar ">

  <nav class= "footer navbar" >

       <li class="nav-item col-lg-12"><%= link_to "Mis cursos", {controller: "contexts", action: "course", id:  cookies[:userid]} %></li>


  </nav>

</nav>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Sortorder</th>
      <th>Fullname</th>
      <th>Shortname</th>
      <th>Idnumber</th>
      <th>Summary</th>
      <th>Summaryformat</th>
      <th>Format</th>
      <th>Showgrades</th>
      <th>Newsitems</th>
      <th>Startdate</th>
      <th>Marker</th>
      <th>Maxbytes</th>
      <th>Legacyfiles</th>
      <th>Showreports</th>
      <th>Visible</th>
      <th>Visibleold</th>
      <th>Groupmode</th>
      <th>Groupmodeforce</th>
      <th>Defaultgroupingid</th>
      <th>Lang</th>
      <th>Calendartype</th>
      <th>Theme</th>
      <th>Timecreated</th>
      <th>Timemodified</th>
      <th>Requested</th>
      <th>Enablecompletion</th>
      <th>Completionnotify</th>
      <th>Cacherev</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.category %></td>
        <td><%= course.sortorder %></td>
        <td><%= course.fullname %></td>
        <td><%= course.shortname %></td>
        <td><%= course.idnumber %></td>
        <td><%= course.summary %></td>
        <td><%= course.summaryformat %></td>
        <td><%= course.format %></td>
        <td><%= course.showgrades %></td>
        <td><%= course.newsitems %></td>
        <td><%= course.startdate %></td>
        <td><%= course.marker %></td>
        <td><%= course.maxbytes %></td>
        <td><%= course.legacyfiles %></td>
        <td><%= course.showreports %></td>
        <td><%= course.visible %></td>
        <td><%= course.visibleold %></td>
        <td><%= course.groupmode %></td>
        <td><%= course.groupmodeforce %></td>
        <td><%= course.defaultgroupingid %></td>
        <td><%= course.lang %></td>
        <td><%= course.calendartype %></td>
        <td><%= course.theme %></td>
        <td><%= course.timecreated %></td>
        <td><%= course.timemodified %></td>
        <td><%= course.requested %></td>
        <td><%= course.enablecompletion %></td>
        <td><%= course.completionnotify %></td>
        <td><%= course.cacherev %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/registerCourse.html.erb
<%= form_for :courses, :url => { :action => :cursos} do |f| %>


<%= stylesheet_link_tag "basePantallas" %>
<div class="contenido container-fluid">
  <div class="row">
    <div class="col-md-12 titulo"><h1>Se ha solicitado la inscripción del curso a su profesor.</h1></div>
  </div>

</div>


<nav class="footer navbar ">

  <nav class= "footer navbar" >

       <li class="nav-item col-lg-12"><%= link_to "Mis cursos", {controller: "contexts", action: "course", id:  cookies[:userid]} %></li>


  </nav>

</nav>

<% end %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @course.category %>
</p>

<p>
  <strong>Sortorder:</strong>
  <%= @course.sortorder %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @course.fullname %>
</p>

<p>
  <strong>Shortname:</strong>
  <%= @course.shortname %>
</p>

<p>
  <strong>Idnumber:</strong>
  <%= @course.idnumber %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @course.summary %>
</p>

<p>
  <strong>Summaryformat:</strong>
  <%= @course.summaryformat %>
</p>

<p>
  <strong>Format:</strong>
  <%= @course.format %>
</p>

<p>
  <strong>Showgrades:</strong>
  <%= @course.showgrades %>
</p>

<p>
  <strong>Newsitems:</strong>
  <%= @course.newsitems %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @course.startdate %>
</p>

<p>
  <strong>Marker:</strong>
  <%= @course.marker %>
</p>

<p>
  <strong>Maxbytes:</strong>
  <%= @course.maxbytes %>
</p>

<p>
  <strong>Legacyfiles:</strong>
  <%= @course.legacyfiles %>
</p>

<p>
  <strong>Showreports:</strong>
  <%= @course.showreports %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @course.visible %>
</p>

<p>
  <strong>Visibleold:</strong>
  <%= @course.visibleold %>
</p>

<p>
  <strong>Groupmode:</strong>
  <%= @course.groupmode %>
</p>

<p>
  <strong>Groupmodeforce:</strong>
  <%= @course.groupmodeforce %>
</p>

<p>
  <strong>Defaultgroupingid:</strong>
  <%= @course.defaultgroupingid %>
</p>

<p>
  <strong>Lang:</strong>
  <%= @course.lang %>
</p>

<p>
  <strong>Calendartype:</strong>
  <%= @course.calendartype %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @course.theme %>
</p>

<p>
  <strong>Timecreated:</strong>
  <%= @course.timecreated %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @course.timemodified %>
</p>

<p>
  <strong>Requested:</strong>
  <%= @course.requested %>
</p>

<p>
  <strong>Enablecompletion:</strong>
  <%= @course.enablecompletion %>
</p>

<p>
  <strong>Completionnotify:</strong>
  <%= @course.completionnotify %>
</p>

<p>
  <strong>Cacherev:</strong>
  <%= @course.cacherev %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/sinCursos.html.erb
<%= stylesheet_link_tag "baseMensajes" %>
<div class="container-fluid">
<div class = "Estilo">


    <div  class="card">


      <div class="card-header"><h1>UPS</h1></div>


      <div class="list-group list-group-flush">

        <div class="list-group-item">


               <div class="col-lg-12"><h1>No hay resultados para tu busqueda, por favor busca nuevamente </h1></div>

               <%= link_to 'Ir a buscar', :back, :class => "btn btn-primary btn-lg btn-block" %>


         </div>
        </div>
        </div>
      </div>
    </div>
  </div>