config/routes.rb
Rails.application.routes.draw do
  resources :assignsubmission_files
  resources :assignment_submissions
  resources :mdl_files
  resources :contexts
  resources :courses do
    member do
      get 'courses/add_course/:id', to: 'courses#addCourse', as: 'add_course'
    end
    collection do
      get 'courses/register_course/:id', to: 'courses#registerCourse', as: 'register_course'
    end
  end
  resources :events
  resources :forum_discussions
  resources :forum_posts
  resources :forums
  resources :resources
  resources :role_assignments
  resources :users

  root 'welcome#index'

  get 'users/vEmail/:id', to: 'users#vEmail'

  get 'users/vContrasena/:email', to: 'users#vContrasena'

  post 'users/contrasena', to: 'users#contrasena'

  post 'users/email', to: 'users#email'

  get 'users/emailErroneo', to: 'users#emailErroneo'

  get 'users/contrasenaErronea', to: 'users#contrasenaErronea'

  get 'contexts/course/:id', to: 'contexts#course'

  get 'resources/recursosPorCurso/:course', to: 'resources#recursosPorCurso'

  get 'events/eventosPorCurso/:courseid', to: 'events#eventosPorCurso'

  get 'events/eventosDetalle/:eventid/:courseid', to: 'events#eventosDetalle'

  get 'forums/forosPorCurso/:course', to: 'forums#forosPorCurso'

  get 'forum_discussions/discusionesPorForo/:forum', to: 'forum_discussions#discusionesPorForo'

  get 'forum_posts/postPorDiscusionPrincipal/:discussion', to: 'forum_posts#postPorDiscusionPrincipal'

  get 'forum_posts/postRespuestas/:discussion', to: 'forum_posts#postRespuestas'

  get 'forum_posts/sinPosts', to: 'forum_posts#sinPosts'

  get 'forum_discussions/sinDiscusiones', to: 'forum_discussions#sinDiscusiones'

  get 'events/sinEventos/:courseid', to: 'events#sinEventos'

  get 'resources/sinRecursos/:course', to: 'resources#sinRecursos'

  get 'contexts/sinCursos/:id', to: 'contexts#sinCursos'

  get 'courses/buscar/:id', to: 'courses#buscar'

  post 'courses/cursos', to: 'courses#cursos'

  get 'courses/sinCursos/', to: 'courses#sinCursos'

  get 'forum_posts/felicitaciones', to: 'forum_posts#felicitaciones'

  get 'forum_posts/error', to: 'forum_posts#error'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  get 'resources/descarga/:course/:timemodified', to: 'resources#descarga'

  get 'resources/descargaINT/:variablePatito', to: 'resources#descargaINT'

  get 'events/emailProf/:id', to: 'events#emailProf'

  post 'events/enviarCorreo', to: 'events#enviarCorreo'

  get 'events/envioExitoso/:courseid', to: 'events#envioExitoso'

  match 'enviarCorreo', to: 'event#send_mail', via: 'post'

  post 'uploadfiles'=>'events#upload'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/context.rb
class Context < ApplicationRecord

  self.table_name = "context"

end

app/models/course.rb
class Course < ApplicationRecord

  self.table_name = "course"

end

app/models/event.rb
class Event < ApplicationRecord

  self.table_name = "event"
  belongs_to :user 

end

app/models/forum.rb
class Forum < ApplicationRecord

  self.table_name = "forum"
  self.inheritance_column = :_type_disabled

end

app/models/forum_discussion.rb
class ForumDiscussion < ApplicationRecord


end

app/models/forum_post.rb
class ForumPost < ApplicationRecord



end

app/models/mdl_file.rb
class MdlFile < ApplicationRecord

  self.table_name = "files"
  belongs_to :ressource

end

app/models/resource.rb
class Resource < ApplicationRecord

 self.table_name = "resource"

 has_many :MdlFile

end

app/models/role_assignment.rb
class RoleAssignment < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord


   self.table_name = "user"
   has_many :events


end

app/controllers/role_assignments_controller.rb
class RoleAssignmentsController < ApplicationController
  before_action :set_role_assignment, only: [:show, :edit, :update, :destroy]

  # GET /role_assignments
  # GET /role_assignments.json
  def index
    @role_assignments = RoleAssignment.all
  end

  # GET /role_assignments/1
  # GET /role_assignments/1.json
  def show
  end

  # GET /role_assignments/new
  def new
    @role_assignment = RoleAssignment.new
  end

  # GET /role_assignments/1/edit
  def edit
  end

  # POST /role_assignments
  # POST /role_assignments.json
  def create
    @role_assignment = RoleAssignment.new(role_assignment_params)

    respond_to do |format|
      if @role_assignment.save
        format.html { redirect_to @role_assignment, notice: 'Role assignment was successfully created.' }
        format.json { render :show, status: :created, location: @role_assignment }
      else
        format.html { render :new }
        format.json { render json: @role_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /role_assignments/1
  # PATCH/PUT /role_assignments/1.json
  def update
    respond_to do |format|
      if @role_assignment.update(role_assignment_params)
        format.html { redirect_to @role_assignment, notice: 'Role assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_assignment }
      else
        format.html { render :edit }
        format.json { render json: @role_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_assignments/1
  # DELETE /role_assignments/1.json
  def destroy
    @role_assignment.destroy
    respond_to do |format|
      format.html { redirect_to role_assignments_url, notice: 'Role assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_assignment
      @role_assignment = RoleAssignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_assignment_params
      params.require(:role_assignment).permit(:roleid, :contextid, :userid, :timemodified, :modifierid, :component, :itemid, :sortorder)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contexts_helper.rb
module ContextsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/mdl_files_helper.rb
module MdlFilesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/role_assignments_helper.rb
module RoleAssignmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/role_assignments/_form.html.erb
<%= form_with(model: role_assignment, local: true) do |form| %>
  <% if role_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role_assignment.errors.count, "error") %> prohibited this role_assignment from being saved:</h2>

      <ul>
      <% role_assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :roleid %>
    <%= form.text_field :roleid %>
  </div>

  <div class="field">
    <%= form.label :contextid %>
    <%= form.text_field :contextid %>
  </div>

  <div class="field">
    <%= form.label :userid %>
    <%= form.text_field :userid %>
  </div>

  <div class="field">
    <%= form.label :timemodified %>
    <%= form.text_field :timemodified %>
  </div>

  <div class="field">
    <%= form.label :modifierid %>
    <%= form.text_field :modifierid %>
  </div>

  <div class="field">
    <%= form.label :component %>
    <%= form.text_field :component %>
  </div>

  <div class="field">
    <%= form.label :itemid %>
    <%= form.text_field :itemid %>
  </div>

  <div class="field">
    <%= form.label :sortorder %>
    <%= form.text_field :sortorder %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/role_assignments/edit.html.erb
<h1>Editing Role Assignment</h1>

<%= render 'form', role_assignment: @role_assignment %>

<%= link_to 'Show', @role_assignment %> |
<%= link_to 'Back', role_assignments_path %>

app/views/role_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Role Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Roleid</th>
      <th>Contextid</th>
      <th>Userid</th>
      <th>Timemodified</th>
      <th>Modifierid</th>
      <th>Component</th>
      <th>Itemid</th>
      <th>Sortorder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @role_assignments.each do |role_assignment| %>
      <tr>
        <td><%= role_assignment.roleid %></td>
        <td><%= role_assignment.contextid %></td>
        <td><%= role_assignment.userid %></td>
        <td><%= role_assignment.timemodified %></td>
        <td><%= role_assignment.modifierid %></td>
        <td><%= role_assignment.component %></td>
        <td><%= role_assignment.itemid %></td>
        <td><%= role_assignment.sortorder %></td>
        <td><%= link_to 'Show', role_assignment %></td>
        <td><%= link_to 'Edit', edit_role_assignment_path(role_assignment) %></td>
        <td><%= link_to 'Destroy', role_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role Assignment', new_role_assignment_path %>

app/views/role_assignments/new.html.erb
<h1>New Role Assignment</h1>

<%= render 'form', role_assignment: @role_assignment %>

<%= link_to 'Back', role_assignments_path %>

app/views/role_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roleid:</strong>
  <%= @role_assignment.roleid %>
</p>

<p>
  <strong>Contextid:</strong>
  <%= @role_assignment.contextid %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @role_assignment.userid %>
</p>

<p>
  <strong>Timemodified:</strong>
  <%= @role_assignment.timemodified %>
</p>

<p>
  <strong>Modifierid:</strong>
  <%= @role_assignment.modifierid %>
</p>

<p>
  <strong>Component:</strong>
  <%= @role_assignment.component %>
</p>

<p>
  <strong>Itemid:</strong>
  <%= @role_assignment.itemid %>
</p>

<p>
  <strong>Sortorder:</strong>
  <%= @role_assignment.sortorder %>
</p>

<%= link_to 'Edit', edit_role_assignment_path(@role_assignment) %> |
<%= link_to 'Back', role_assignments_path %>